package com.example.findAnswer.mentorbridge.constants;

public enum NotificationType {
    NEW_ANSWER,
    QUESTION_LIKED,
    MENTOR_APPLICATION_SUBMITTED,
    MENTOR_APPROVED,
    MENTOR_REJECTED,
    NEW_FOLLOWER,
    PAYMENT_SUCCESS,
    NEW_SUBSCRIBER,
    PAYMENT_FAILED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,
    NEW_CHAT_MESSAGE,
    NEW_MENTOR_POST,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
}
