spring:
  application:
    name: findAnswer

  datasource:
    url: jdbc:mysql://dev-db-instance.cl8i8mcky5jd.ap-northeast-2.rds.amazonaws.com:3306/dev_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: qwer1234 #비밀번호 빼고 docker compose에서 넣게끔
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: findanswer-jwt-secret-key-please-change-this-later-32bytes-ok